export type assignment = {
  id: number;
  due_at: string;
  unlock_at?: string;
  lock_at?: string;
  created_at: string;
  updated_at: string;
  anonymous_grading: boolean;
  graders_anonymous_to_graders: boolean;
  course_id: number;
  name: string;
  has_submitted_submissions: boolean;
  graded_submissions_exist: false;
  is_quiz_assignment: false;
  workflow_state: string;
  muted: boolean;
  integration_id?: null;
  integration_data?: any;
  published: boolean;
  unpublishable: boolean;
  post_manually: boolean;
  anonymize_students: boolean;
  require_lockdown_browser: boolean;
};
export type submission = {
  id: number;
  workflow_state: string;
};
export type course = {
  id: number;
  name: string;
  account_id: number;
  start_at: string;
  is_public: boolean;
  created_at: string;
  course_code: string;
  root_account_id: 1;
  end_at: null;
  sis_course_id: string;
  workflow_state: "available";
};
